FEATURE: Custom Class for both slider and slides
noerdisch/neos-slick pull request #5
Opened 2018-09-17 11:55 UTC by abteilung

Custom Classes for both slider and individual slides. Now you can apply custom styles to individual slide(r)s.

2018-09-17 12:13 UTC, breadlesscode requested changes
Please fix that small issues :) Thanks for your PR! 👍

2018-09-17 12:13 UTC, breadlesscode commented on Configuration/NodeTypes.Content.Slide.yaml
> +          icon: 'icon-images'
This icon should be icon-picture ;)

2018-09-17 12:13 UTC, breadlesscode commented on Resources/Private/Fusion/Slide.fusion
> +                    additionalClass = ${node.properties.additionalClass}
Please use flow query to access the property.

2018-09-17 12:13 UTC, breadlesscode commented on Resources/Private/Fusion/Slider.fusion
> +        attributes.class = ${node.properties.additionalClass}
Same here. Please use flow query to access the property

2018-09-18 07:38 UTC, breadlesscode approved these changes

2018-09-18 08:20 UTC, breadlesscode approved these changes

2018-09-18 08:21 UTC, breadlesscode approved these changes

2018-09-18 08:23 UTC, merged

2018-09-18 08:26 UTC, markusguenther commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/noerdisch/neos-slick/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2018-09-18 08:42 UTC, markusguenther commented
Created a small issue to improve the docs. But great that you have added this feature :)
Thank you 🙏

2018-09-19 09:04 UTC, abteilung commented
@markusguenther There's a typo in the flow query string in Slider.fusion. Sorry about that.

2018-09-19 09:10 UTC, breadlesscode commented
@abteilung can you send a PR?